export const AUDIT_ACTIONS = {
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILURE: "AUTH_LOGIN_FAILURE",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  FIRST_ACCESS_PASSWORD_CHANGED: "FIRST_ACCESS_PASSWORD_CHANGED",
  IMPERSONATION_STARTED: "IMPERSONATION_STARTED",
  IMPERSONATION_STOPPED: "IMPERSONATION_STOPPED",
  MATCH_LIVE_UPDATED: "MATCH_LIVE_UPDATED",
  CLUB_ATHLETE_CREATED: "CLUB_ATHLETE_CREATED",
  CLUB_ATHLETE_UPDATED: "CLUB_ATHLETE_UPDATED",
  CLUB_ATHLETE_DELETED: "CLUB_ATHLETE_DELETED",
  SYSTEM_SETTING_UPDATED: "SYSTEM_SETTING_UPDATED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
